"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowser } from "../../lib/supabase-browser";

export default function NotesPage(){
 const [user,setUser]=useState(null),[folders,setFolders]=useState([]),[notes,setNotes]=useState([]),[folder,setFolder]=useState(null),[selected,setSelected]=useState(null),[name,setName]=useState(""),[title,setTitle]=useState(""),[content,setContent]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("");
 const supabase=getSupabaseBrowser();
 useEffect(()=>{load();},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user)return;const f=await supabase.from("note_folders").select("*").order("created_at");const n=await supabase.from("notes").select("*").order("updated_at",{ascending:false});setFolders(f.data||[]);setNotes(n.data||[]);if(f.data?.[0])setFolder(f.data[0]);}
 async function addFolder(){if(!name.trim()||!user)return;const {data,error}=await supabase.from("note_folders").insert({name:name.trim(),user_id:user.id}).select().single();if(error)return setStatus(error.message);setFolders(x=>[...x,data]);setFolder(data);setName("");setStatus("📁 Folder utworzony!");}
 function openNote(n){setSelected(n);setTitle(n.title);setContent(n.content);setStatus("");}
 async function save(){if(!selected)return;const {data,error}=await supabase.from("notes").update({title,content,updated_at:new Date().toISOString()}).eq("id",selected.id).select().single();if(error)return setStatus(error.message);setNotes(x=>x.map(n=>n.id===data.id?data:n));setSelected(data);setStatus("💾 Zapisano!");}
 async function addNote(){if(!folder||!user)return;const {data,error}=await supabase.from("notes").insert({folder_id:folder.id,user_id:user.id,title:"Nowa notatka",content:""}).select().single();if(error)return setStatus(error.message);setNotes(x=>[data,...x]);openNote(data);}
 async function removeNote(){if(!selected)return;await supabase.from("notes").delete().eq("id",selected.id);setNotes(x=>x.filter(n=>n.id!==selected.id));setSelected(null);setStatus("🗑️ Usunięto!");}
 const visible=notes.filter(n=>(!folder||n.folder_id===folder.id)&&(`${n.title} ${n.content}`).toLowerCase().includes(query.toLowerCase()));
 if(!user)return <main className="shell"><div className="notesEmpty"><h1>📝 Nexoras Notatnik</h1><p>Zaloguj się, żeby korzystać z własnych folderów i notatek.</p><a href="/auth">🔐 Zaloguj się</a></div></main>;
 return <main className="shell"><header className="topbar"><div className="logo">NEXORAS <span>NOTES</span></div><a className="profile" href="/">← Nexoras</a></header><section className="notesPage"><div className="kicker">📝 TWOJA PRZESTRZEŃ</div><h1>Notatnik</h1><p>Foldery, pomysły i notatki. Wszystko zapisuje się w chmurze.</p><div className="notesToolbar"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nazwa folderu..." onKeyDown={e=>e.key==="Enter"&&addFolder()}/><button onClick={addFolder}>＋ Folder</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Szukaj..."/><button onClick={addNote} disabled={!folder}>＋ Notatka</button></div><div className="notesLayout"><aside className="folders"><h3>📁 Foldery</h3>{folders.map(f=><button key={f.id} className={folder?.id===f.id?"selectedProject":""} onClick={()=>{setFolder(f);setSelected(null)}}>📁 {f.name}</button>)}</aside><section className="notesList"><h3>{folder?.name||"Wybierz folder"}</h3>{visible.map(n=><button className={selected?.id===n.id?"note selectedNote":"note"} key={n.id} onClick={()=>openNote(n)}>📝 <b>{n.title}</b><small>{n.content.slice(0,70)||"Pusta notatka"}</small></button>)}{!visible.length&&<p>Brak notatek. Kliknij „＋ Notatka”. 🚀</p>}</section><section className="editor">{selected?<><input className="noteTitle" value={title} onChange={e=>setTitle(e.target.value)}/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Zacznij pisać..."/><div><button onClick={save}>💾 Zapisz</button><button onClick={removeNote}>🗑️ Usuń</button></div></>:<div className="editorEmpty">Wybierz notatkę albo utwórz nową ✨</div>}<p>{status}</p></section></div></section></main>;
}