"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowser} from "../../lib/supabase-browser";

function isOnline(lastSeen){return lastSeen&&Date.now()-new Date(lastSeen).getTime()<2*60*1000}
function activityText(lastSeen){if(isOnline(lastSeen))return "🟢 Online teraz";if(!lastSeen)return "⚪ Brak aktywności";const minutes=Math.max(1,Math.floor((Date.now()-new Date(lastSeen).getTime())/60000));return minutes<60?`⚪ Aktywny ${minutes} min temu`:`⚪ Aktywny ${Math.floor(minutes/60)} godz. temu`}

export default function Community(){
 const [users,setUsers]=useState([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let timer;const load=async()=>{try{const s=getSupabaseBrowser();const{data:{user}}=await s.auth.getUser();if(user)await s.from("profiles").update({last_seen_at:new Date().toISOString()}).eq("id",user.id);const{data,error}=await s.from("profiles").select("id,username,display_name,avatar_url,created_at,last_seen_at").order("last_seen_at",{ascending:false,nullsFirst:false});if(error)throw error;setUsers(data||[])}catch(e){setError(e.message||"Nie udało się pobrać użytkowników.")}finally{setLoading(false)}};load();timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const list=users.filter(u=>`${u.username||""} ${u.display_name||""}`.toLowerCase().includes(q.toLowerCase()));
 return <main className="shell"><header className="topbar"><div className="logo">NEXORAS <span>COMMUNITY</span></div><a className="profile" href="/">← Nexoras</a></header><section className="notesPage"><div className="kicker">🌐 NEXORAS COMMUNITY</div><h1>Użytkownicy</h1><p>Poznaj ludzi tworzących Nexorasa. Status aktualizuje się automatycznie.</p><div className="notesToolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Szukaj po nicku..."/></div>{loading?<p>Ładowanie użytkowników... 🛰️</p>:error?<p>⚠️ {error}</p>:<><div className="communityStats"><b>{users.length}</b><span>użytkowników</span><b>{users.filter(u=>isOnline(u.last_seen_at)).length}</b><span>online</span></div><div className="userGrid">{list.map(u=><a className="userCard" href={`/profile/${u.username||u.id}`} key={u.id}><div className="avatar">{u.avatar_url?<img src={u.avatar_url} alt=""/>:"👤"}</div><div><b>{u.display_name||u.username||"Nexorian"}</b><small>@{u.username||"user"}</small><span>{activityText(u.last_seen_at)}</span></div></a>)}{!list.length&&<p>Nie znaleziono użytkownika. 👻</p>}</div></>}</section></main>
}