"use client";

import { useEffect, useRef, useState } from "react";

const cards = [["🎮","Gry","Kółko-krzyżyk z AI i kolejne gry."],["🤖","AI Chat","Darmowy chat AI prosto z Nexorasa."],["💡","Pomysły","Twórz projekty i rozwijaj je ze społecznością."],["📻","Radio","Nexoras Radio z bangerami."],["📝","Notatnik","Twoje notatki i foldery."],["🧰","Narzędzia","Przydatne narzędzia w jednym miejscu."]];
const tracks=[{title:"Kizo – Disney",artist:"Kizo",src:"/audio/Kizo%20-%20Disney.mp3"},{title:"Oki – Jakie To Uczucie?",artist:"Oki",src:"/audio/OKI%20-%20Jakie%20To%20Uczucie_.mp3"}];
const emptyBoard=Array(9).fill(null);
function winner(board){const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(const[a,b,c]of lines)if(board[a]&&board[a]===board[b]&&board[a]===board[c])return board[a];return board.every(Boolean)?"draw":null;}
function aiMove(board){const free=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(!free.length)return board;for(const i of free){const test=[...board];test[i]="O";if(winner(test)==="O")return test;}for(const i of free){const test=[...board];test[i]="X";if(winner(test)==="X"){const next=[...board];next[i]="O";return next;}}const preferred=[4,0,2,6,8,1,3,5,7].filter(i=>!board[i]);const i=preferred[Math.floor(Math.random()*Math.min(preferred.length,3))];const next=[...board];next[i]="O";return next;}

export default function Home(){
 const[toast,setToast]=useState("");const[gameOpen,setGameOpen]=useState(false);const[ideasOpen,setIdeasOpen]=useState(false);const[chatOpen,setChatOpen]=useState(false);const[radioOpen,setRadioOpen]=useState(false);const[board,setBoard]=useState(emptyBoard);const[thinking,setThinking]=useState(false);const[projects,setProjects]=useState([]);const[selectedProject,setSelectedProject]=useState(0);const[newProject,setNewProject]=useState("");const[newIdea,setNewIdea]=useState("");const[loadingIdeas,setLoadingIdeas]=useState(false);const[secret,setSecret]=useState(false);const[messages,setMessages]=useState([{role:"ai",text:"🤖 Cześć! Jestem Nexoras AI. Co budujemy?"}]);const[chatInput,setChatInput]=useState("");const[chatLoading,setChatLoading]=useState(false);const[audioIndex,setAudioIndex]=useState(0);const[playing,setPlaying]=useState(false);const[shuffle,setShuffle]=useState(false);const[volume,setVolume]=useState(0.8);const audioRef=useRef(null);
 function click(message){setToast(message);window.setTimeout(()=>setToast(""),1800)}function resetGame(){setBoard(emptyBoard);setThinking(false)}
 useEffect(()=>{fetch("/api/ideas").then(r=>r.ok?r.json():Promise.reject()).then(d=>setProjects(d.projects||[])).catch(()=>click("⚠️ Ideas API czeka na zmienne Supabase."))},[]);
 useEffect(()=>{if(audioRef.current)audioRef.current.volume=volume},[volume]);
 function playerMove(index){if(thinking||board[index]||winner(board))return;const next=[...board];next[index]="X";setBoard(next);const result=winner(next);if(result){click(result==="X"?"🏆 WYGRANA! AI dostało po głowie.":"🤝 Remis!");return}setThinking(true);window.setTimeout(()=>{const afterAI=aiMove(next);setBoard(afterAI);setThinking(false);const r=winner(afterAI);if(r)click(r==="O"?"🤖 AI WYGRYWA! Rewanż?":"🤝 Remis!")},450)}
 async function addProject(){const name=newProject.trim();if(!name)return;setLoadingIdeas(true);try{const r=await fetch("/api/ideas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"project",name})});const project=await r.json();if(!r.ok)throw new Error(project.error);setProjects(current=>[...current,{...project,ideas:[]}]);setSelectedProject(projects.length);setNewProject("");click("📁 Projekt zapisany w Nexoras!")}catch(e){click(`⚠️ ${e.message}`)}finally{setLoadingIdeas(false)}}
 async function addIdea(){const text=newIdea.trim(),project=projects[selectedProject];if(!text||!project)return;setLoadingIdeas(true);try{const r=await fetch("/api/ideas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"idea",projectId:project.id,text,authorName:"Anonim"})});const idea=await r.json();if(!r.ok)throw new Error(idea.error);setProjects(current=>current.map((item,index)=>index===selectedProject?{...item,ideas:[...(item.ideas||[]),idea]}:item));setNewIdea("");click("💡 Propozycja zapisana na stałe!")}catch(e){click(`⚠️ ${e.message}`)}finally{setLoadingIdeas(false)}}
 async function sendChat(){const text=chatInput.trim();if(!text||chatLoading)return;const previous=messages;setMessages(m=>[...m,{role:"user",text}]);setChatInput("");setChatLoading(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:previous})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessages(m=>[...m,{role:"ai",text:data.answer}])}catch(e){setMessages(m=>[...m,{role:"ai",text:`⚠️ ${e.message}`}])}finally{setChatLoading(false)}}
 function playTrack(index=audioIndex){const audio=audioRef.current;if(!audio)return;setAudioIndex(index);audio.src=tracks[index].src;audio.volume=volume;audio.play().then(()=>setPlaying(true)).catch(()=>click("🎵 Nie udało się odtworzyć pliku MP3."));}
 function nextTrack(){const next=shuffle?Math.floor(Math.random()*tracks.length):(audioIndex+1)%tracks.length;playTrack(next)} function prevTrack(){playTrack((audioIndex-1+tracks.length)%tracks.length)} function togglePlay(){if(!audioRef.current)return;if(playing){audioRef.current.pause();setPlaying(false)}else playTrack(audioIndex)}
 const quickPrompts=["💡 Wymyśl funkcję dla Nexorasa","🎮 Jaką grę dodajemy?","🧠 Pomóż mi coś zaplanować"];
 return <main className="shell"><audio ref={audioRef} onEnded={nextTrack}/><header className="topbar"><div className="logo">NEXORAS <span>COMMUNITY</span></div><nav className="nav"><button onClick={()=>setGameOpen(true)}>Gry</button><button onClick={()=>setIdeasOpen(true)}>Pomysły</button><button onClick={()=>setChatOpen(true)}>AI</button><button onClick={()=>setRadioOpen(true)}>Radio</button><a href="/community">Community</a><a href="/tools">Narzędzia</a></nav><a className="profile" href="/profile">Profil</a></header>
 <section className="hero"><div className="kicker">Nexoras Community • v0.8</div><h1>Jedno miejsce.<br/>Dużo możliwości.</h1><p>Gry, AI, radio, pomysły i społeczność. Każdy klik może coś odpalić. 👀</p></section>
 <section className="grid">{cards.map(([icon,title,description])=><article className="card" key={title}><div className="icon">{icon}</div><h2>{title}</h2><p>{description}</p><button onClick={()=>title==="Gry"?setGameOpen(true):title==="Pomysły"?setIdeasOpen(true):title==="AI Chat"?setChatOpen(true):title==="Radio"?setRadioOpen(true):title==="Notatnik"?location.href="/notes":title==="Narzędzia"?location.href="/tools":click(`${icon} ${title}: nadchodzimy!`)}>Otwórz</button></article>)}<article className="card wide radio"><div><div className="icon">🔊</div><h2>Nexoras Radio</h2><p>Teraz: <strong>{tracks[audioIndex].title}</strong> • {tracks[audioIndex].artist}</p></div><button className="play" onClick={()=>setRadioOpen(true)}>{playing?"⏸":"▶"}</button></article><article className={`card secret ${secret?"secretActive":""}`} onClick={()=>{setSecret(true);click("🗿 SIX SEVEN! Odkryłeś sekret #07.")}}><div className="icon">🟪</div><h2>SIX SEVEN</h2><p>{secret?"6️⃣ 7️⃣ SEKRET ODKRYTY!":"To wygląda jak zwykła karta. Kliknij, jeśli masz odwagę."}</p></article></section>
 {radioOpen&&<div className="gameOverlay"><div className="ideasPanel radioPanel"><button className="close" onClick={()=>setRadioOpen(false)}>✕</button><div className="kicker">📻 NEXORAS RADIO</div><h2>{tracks[audioIndex].title}</h2><p>{tracks[audioIndex].artist}</p><div className="radioControls"><button onClick={prevTrack}>⏮</button><button className="mainPlay" onClick={togglePlay}>{playing?"⏸":"▶"}</button><button onClick={nextTrack}>⏭</button></div><div className="radioTools"><button onClick={()=>setShuffle(!shuffle)}>{shuffle?"🔀 ON":"🔀 OFF"}</button><label>🔊 <input type="range" min="0" max="1" step="0.01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label></div><div className="trackList">{tracks.map((track,i)=><button key={track.title} className={i===audioIndex?"activeTrack":""} onClick={()=>playTrack(i)}>🎵 {track.title}<small>{track.artist}</small></button>)}</div><p className="radioHint">Pliki MP3 są w <code>public/audio/</code>. 🎧</p></div></div>}
 {gameOpen&&<div className="gameOverlay"><div className="gamePanel"><button className="close" onClick={()=>setGameOpen(false)}>✕</button><div className="kicker">🎮 NEXORAS GAMES</div><h2>Kółko i krzyżyk</h2><p>Ty: ❌ X • AI: ⭕ O</p><div className="board">{board.map((value,index)=><button key={index} className="cell" onClick={()=>playerMove(index)}>{value}</button>)}</div><p className="gameStatus">{thinking?"🤖 AI myśli...":winner(board)==="X"?"🏆 Wygrałeś!":winner(board)==="O"?"🤖 AI wygrało!":winner(board)==="draw"?"🤝 Remis!":"Twój ruch, szefie."}</p><button className="reset" onClick={resetGame}>🔄 Nowa gra</button></div></div>}
 {ideasOpen&&<div className="gameOverlay"><div className="ideasPanel"><button className="close" onClick={()=>setIdeasOpen(false)}>✕</button><div className="kicker">💡 NEXORAS IDEAS</div><h2>Pomysły społeczności</h2><div className="projectCreator"><input value={newProject} onChange={e=>setNewProject(e.target.value)} placeholder="Nazwa projektu, np. Firma: Stacja benzynowa"/><button disabled={loadingIdeas} onClick={addProject}>{loadingIdeas?"Zapisuję...":"＋ Utwórz folder"}</button></div><div className="ideasLayout"><aside>{projects.map((p,i)=><button key={p.id} className={i===selectedProject?"selectedProject":""} onClick={()=>setSelectedProject(i)}>📁 {p.name}</button>)}</aside><section className="ideaList">{projects[selectedProject]?<><h3>{projects[selectedProject].name}</h3>{(projects[selectedProject].ideas||[]).map((idea,i)=><div className="idea" key={idea.id||`${idea.text}-${i}`}>💡 {idea.text} <small>• {idea.author_name}</small></div>)}<div className="ideaCreator"><input value={newIdea} onChange={e=>setNewIdea(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addIdea()} placeholder="Wpisz swoją propozycję..."/><button disabled={loadingIdeas} onClick={addIdea}>Dodaj</button></div></>:<p>Brak projektów. Utwórz pierwszy! 🚀</p>}</section></div></div></div>}
 {chatOpen&&<div className="gameOverlay"><div className="ideasPanel chatPanel"><button className="close" onClick={()=>setChatOpen(false)}>✕</button><div className="kicker">🤖 NEXORAS AI</div><h2>Chat AI</h2><div className="quickPrompts">{quickPrompts.map(prompt=><button key={prompt} onClick={()=>setChatInput(prompt.replace(/^\S+\s/,""))}>{prompt}</button>)}</div><div className="chatMessages">{messages.map((m,i)=><div key={i} className={`chatMessage ${m.role}`}>{m.text}</div>)}{chatLoading&&<div className="chatMessage ai">🤖 Myślę...</div>}</div><div className="ideaCreator"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendChat()} placeholder="Napisz do Nexoras AI..."/><button disabled={chatLoading} onClick={sendChat}>Wyślij</button></div></div></div>}
 {toast&&<div className="toast">{toast}</div>}</main>;
}
