"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowser } from "../../lib/supabase-browser";

export default function MessagesPage() {
  const [me,setMe]=useState(null),[users,setUsers]=useState([]),[selected,setSelected]=useState(null),[conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[input,setInput]=useState(""),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sending,setSending]=useState(false);
  useEffect(()=>{(async()=>{try{const s=getSupabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user) throw new Error("Zaloguj się, aby korzystać z wiadomości.");setMe(user);const {data,error}=await s.from("profiles").select("id,username,display_name,avatar_url").neq("id",user.id).order("display_name");if(error)throw error;setUsers(data||[])}catch(e){setError(e.message||"Nie udało się załadować wiadomości.")}finally{setLoading(false)}})()},[]);
  async function openChat(user){setSelected(user);setMessages([]);try{const s=getSupabaseBrowser();let {data,error}=await s.from("conversations").select("id,user_one,user_two").or(`and(user_one.eq.${me.id},user_two.eq.${user.id}),and(user_one.eq.${user.id},user_two.eq.${me.id})`).maybeSingle();if(error)throw error;if(!data){const pair=me.id<user.id?[me.id,user.id]:[user.id,me.id];const created=await s.from("conversations").insert({user_one:pair[0],user_two:pair[1]}).select().single();if(created.error)throw created.error;data=created.data}setConversation(data);const loaded=await s.from("messages").select("id,sender_id,body,created_at").eq("conversation_id",data.id).order("created_at");if(loaded.error)throw loaded.error;setMessages(loaded.data||[])}catch(e){setError(e.message||"Nie udało się otworzyć rozmowy.")}}
  async function send(){const body=input.trim();if(!body||!conversation||sending)return;setSending(true);try{const s=getSupabaseBrowser();const {data,error}=await s.from("messages").insert({conversation_id:conversation.id,sender_id:me.id,body}).select().single();if(error)throw error;setMessages(m=>[...m,data]);setInput("")}catch(e){setError(e.message||"Nie udało się wysłać wiadomości.")}finally{setSending(false)}}
  const filtered=users.filter(u=>`${u.username||""} ${u.display_name||""}`.toLowerCase().includes(q.toLowerCase()));
  return <main className="shell"><header className="topbar"><div className="logo">NEXORAS <span>COMMUNITY</span></div><a className="profile" href="/community">← Społeczność</a></header><section className="messagesPage"><div className="kicker">💬 NEXORAS MESSAGES</div><h1>Wiadomości prywatne</h1><p>Rozmawiaj 1:1 z ludźmi z Nexorasa.</p>{loading?<p>Ładowanie... 🛰️</p>:error&&!me?<div className="profileError"><div className="icon">🔐</div><h2>Wymagane logowanie</h2><p>⚠️ {error}</p></div>:<div className="messagesLayout"><aside className="peoplePanel"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 Szukaj użytkownika..."/>{filtered.map(u=><button key={u.id} className={selected?.id===u.id?"selectedPerson":""} onClick={()=>openChat(u)}><div className="avatar">{u.avatar_url?<img src={u.avatar_url} alt=""/>:"👤"}</div><span><b>{u.display_name||u.username||"Nexorian"}</b><small>@{u.username||"user"}</small></span></button>)}{!filtered.length&&<p>Brak użytkowników.</p>}</aside><section className="conversationPanel">{selected?<><div className="conversationHeader"><div className="avatar">{selected.avatar_url?<img src={selected.avatar_url} alt=""/>:"👤"}</div><div><b>{selected.display_name||selected.username}</b><small>@{selected.username}</small></div></div><div className="messageList">{messages.length?messages.map(m=><div key={m.id} className={`bubble ${m.sender_id===me.id?"mine":"theirs"}`}>{m.body}<small>{new Date(m.created_at).toLocaleString("pl-PL")}</small></div>):<p className="emptyChat">To początek rozmowy. Napisz coś! 👋</p>}</div><div className="messageComposer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} maxLength={2000} placeholder="Napisz wiadomość..."/><button disabled={sending} onClick={send}>{sending?"...":"Wyślij"}</button></div></>:<div className="emptyChat"><div className="icon">💬</div><h2>Wybierz osobę</h2><p>Wybierz użytkownika po lewej, aby rozpocząć prywatną rozmowę.</p></div>}</section></div>}</section></main>}
